# Generated by Django 5.2.6 on 2025-10-22 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_wishlist_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date']},
        ),
    ]
