# Generated by Django 5.2.6 on 2025-10-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelled_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
